language: node_js
node_js:
  - "7.4.0"
install:
  - "npm install"
  - "npm install bower -g"
  - "bower install"
  - "gem install scss-lint"
script:
  - "gulp"
  - "gulp test"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
